name       : perl-dbd-mysql
version    : 4.044
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/C/CA/CAPTTOFU/DBD-mysql-4.044.tar.gz : 913d569a5eb018883c1dbe97315f21b002fdf8db4e5731db458d8807a1c828ae
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : A MySQL interface for Perl
description: |
    DBD::mysql is the Perl Database Interface driver for the MySQL database. In
    other words: DBD::mysql is an interface between the Perl programming language
    and the MySQL programming API that comes with the MySQL relational database
    management system. This module is also suitable for MariaDB.
builddeps  :
    - pkgconfig(mariadb)
    - perl-dbi
rundeps    :
    - perl-dbi
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
